name: NodeJS with Webpack

on:
  push:
    branches: [ "new_platform" ]
  pull_request:
    branches: [ "new_platform" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        # Artifact name
        name: GitHub Pages
        # Path of the directory containing the static assets.
        path: './public'
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v3.0.1
          

          
